### ISSUE TITLE
RAM issue

### ISSUE THREAD

**Issue by UrkiMimi** [halsafar/BeatSaberSongDataCore#11]
RAM gets more filled up when you adjust graphical settings.
![image](https://user-images.githubusercontent.com/74517821/127965288-d2865161-3a8f-42cc-b6ef-11c10c0e89fc.png)

**Comment by halsafar** [comment]
Fixed this in commit 85da91c706ff94825edc65b777e301828f86993d, failed to mention this ticket.

Will be doing a release this weekend, will update here when it goes out.

**Comment by halsafar** [comment]
Give this release a try, let me know: https://github.com/halsafar/BeatSaberSongDataCore/releases/tag/1.4.2

**Comment by halsafar** [comment]
Also just released https://github.com/halsafar/BeatSaberSongDataCore/releases/tag/1.4.3 which should help this issue further.
