### ISSUE TITLE
Star ratings not available for any recently ranked map

### ISSUE THREAD

**Issue by ChrisJAllan** [halsafar/BeatSaberSongDataCore#15]
From what I can tell, no maps ranked in the past year or so have a star rating. They have a `pp` value, but `star` is always 0.

**Comment by WesVleuten** [comment]
Thanks for reporting! I'll have a look at this in the coming weekend

**Comment by WesVleuten** [comment]
Sorry about the delay, but data should be fully up to date again and stars are included for ranked maps!

**Comment by ChrisJAllan** [comment]
It looks like the beatstar cdn is still serving an old version: `last-modified | Thu, 30 Sep 2021 08:35:32 GMT`

**Comment by ChrisJAllan** [comment]
Alright, looks like it's fixed!

**Comment by WesVleuten** [comment]
Yeah it takes a while for the cdn caches to get updated, it has some quite aggressive caching set up
