### ISSUE TITLE
ScoreSaber PP Are all 0

### ISSUE THREAD

**Issue by denpadokei** [halsafar/BeatSaberSongDataCore#6]
The pp of the acquired json is all 0.

https://cdn.wes.cloud/beatstar/bssb/v2-all.json

**Comment by WesVleuten** [comment]
Thank you for bringing this to my attention.

I've implemented a short term fix so the values should reappear after a cache refresh and I'll be contacting the folks over at ScoreSaber to work on a long term solution.

This issue should remain open untill the long term solution is implemented.

**Comment by denpadokei** [comment]
Thank you for your support.
I confirmed that I was able to obtain PP.
