### ISSUE TITLE
Text Overlaps In OBS Browser for Data Puller

### ISSUE THREAD

**Issue by idle-Mercy** [halsafar/BeatSaberSongDataCore#7]
I can't seem to get the overlay to not overlap. The preview when I'm selecting to copy paste looks great on the website, but when I actually am in the game, I get the words to all overlap. I went as far as to make the Text Background Transparent so it doesn't look as bad, but I just can't get it to not overlap text. Like, song name and scores overlap terribly. 
Any fix to this? The NJS BPM etc on the bottom line are hardly ever going to show no matter what unless it looks like the preview (so I disabled it. There are times I may get super lucky to have it show, but then the combo or score don't show) And the Combo is just lost for good most of the time. It is a really good overlay though and I want to continue using it. I like the customizability of it way more than the other one available for data puller. I just can't seem to get the text to not overlap. And yes, I tried resizing it. It was originally smaller. Still no luck though. 

![Overlay Issues 3](https://user-images.githubusercontent.com/52788111/99487268-89f80f00-292b-11eb-9370-819a32adf14e.PNG)
![Overlay Issues 4](https://user-images.githubusercontent.com/52788111/99487270-8a90a580-292b-11eb-9539-36cb91c77600.PNG)

**Comment by halsafar** [comment]
Hey there, unfortunately I'm sure how this applies to SongDataCore.  If I'm missing something feel free to re open the issue.
