### ISSUE TITLE
Gzipping downloads?

### ISSUE THREAD

**Issue by kinsi55** [halsafar/BeatSaberSongDataCore#8]
Unless I'm missing something, is there a reason the request to stuff like `https://cdn.wes.cloud/beatstar/bssb/v2-all.json` doesnt accept gzip as the encoding? Would bring the download down to like 3mb instead of >20 saving a lot of traffic and loading time.

**Comment by halsafar** [comment]
This went out with the last SDC release.  https://github.com/halsafar/BeatSaberSongDataCore/releases/tag/1.4.1
